export const GET_ALL_CONFIRMANTES = "GET_ALL_CONFIRMANTES"
export const GET_ALL_GROUPS = "GET_ALL_GROUPS"
export const GET_ALL_ATTENDANCES = "GET_ALL_ATTENDANCES"
export const GET_ALL_CATEQUISTAS = "GET_ALL_CATEQUISTAS"

export const GET_CONFIRMANTE = "GET_CONFIRMANTE"
export const GET_GROUP = "GET_GROUP"
export const GET_ATTENDANCE = "GET_ATTENDANCE"
export const GET_CATEQUISTA = "GET_CATEQUISTA"
